@echo off
echo Starting Ludo Performance Testing Suite...

echo Starting Backend...
start "Backend" cmd /k "cd backend && venv\Scripts\activate && python app.py"

echo Starting Frontend...
start "Frontend" cmd /k "cd frontend && npm start"

echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000
pause
